### ISSUE TITLE
Please update bindgen dependency version

### ISSUE THREAD

**Issue by lluvz** [rust-av/x264-rs#35]
I'm currently trying to use vl4 to get the video from a camera and x264 to encode it, but x264-sys's bindgen dependency is older the v4l, so it conflicts. Could you please update the version of bindgen dependency to 0.65?

**Comment by lu-zero** [comment]
Sure, thank you for reminding me :)

**Comment by lu-zero** [comment]
Done, let me know if it works fine for you :)

**Comment by lluvz** [comment]
It works

**Comment by lluvz** [comment]
Thanks for fixing this issue.
