### ISSUE TITLE
couldn't build on Windows 10 system

### ISSUE THREAD

**Issue by mallochine** [rust-av/x264-rs#4]
error: failed to run custom build command for 'x264-sys v0.1.0

panicked on an Err value Error(PkgConfig(MSVC))

**Comment by lu-zero** [comment]
I'd need more context to be sure but, my guess is that you do not have pkg-config installed or it is not finding x264.

**Comment by mallochine** [comment]
pretty good guess. I have pkg-config but not x264. And wow, installing x264 looks like such a PITA. Am I missing something easy or obvious here? I couldn't find the *.a or *.h files so I'm trying to build from source but running into a problem.

**Comment by lu-zero** [comment]
You may to use [msys2](http://www.msys2.org/) in mingw64 mode, install nasm from inside it and run the normal configure (with `--enable-static and --enable-shared`) and run `make` to build the library with the tools provided there.

Then you should have everything needed.

**Comment by lu-zero** [comment]
If you manage to succeeded I might ask to write some documentation about it so others will spare some confusion :)

**Comment by mallochine** [comment]
I just decided not to use H264 since I had to figure out how to install the x264 libraries. And x264 is GPL.
